[2024-06-10T14:19:10.512+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T14:19:10.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:18:45.755476+00:00 [queued]>
[2024-06-10T14:19:10.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:18:45.755476+00:00 [queued]>
[2024-06-10T14:19:10.548+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T14:19:10.568+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): consolidate_data> on 2024-06-10 14:18:45.755476+00:00
[2024-06-10T14:19:10.575+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T14:19:10.577+0000] {standard_task_runner.py:63} INFO - Started process 243 to run task
[2024-06-10T14:19:10.577+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'consolidate_data', 'manual__2024-06-10T14:18:45.755476+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmp50nug6xh']
[2024-06-10T14:19:10.578+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask consolidate_data
[2024-06-10T14:19:10.622+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:18:45.755476+00:00 [running]> on host 2c4b4cb333a5
[2024-06-10T14:19:10.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='21521333@gm.uit.edu.vn' AIRFLOW_CTX_DAG_OWNER='quan' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='consolidate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T14:18:45.755476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T14:18:45.755476+00:00'
[2024-06-10T14:19:10.713+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T14:19:10.771+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T14:19:10.772+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T14:19:10.784+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data, task_id=consolidate_data, run_id=manual__2024-06-10T14:18:45.755476+00:00, execution_date=20240610T141845, start_date=20240610T141910, end_date=20240610T141910
[2024-06-10T14:19:10.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T14:19:10.853+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-10T14:19:10.856+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
