[2024-06-10T14:19:12.733+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T14:19:12.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.transform_data manual__2024-06-10T14:18:45.755476+00:00 [queued]>
[2024-06-10T14:19:12.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.transform_data manual__2024-06-10T14:18:45.755476+00:00 [queued]>
[2024-06-10T14:19:12.774+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T14:19:12.793+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-06-10 14:18:45.755476+00:00
[2024-06-10T14:19:12.803+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=244) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T14:19:12.804+0000] {standard_task_runner.py:63} INFO - Started process 246 to run task
[2024-06-10T14:19:12.806+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'transform_data', 'manual__2024-06-10T14:18:45.755476+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpuqus19c0']
[2024-06-10T14:19:12.807+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask transform_data
[2024-06-10T14:19:12.856+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_toll_data.transform_data manual__2024-06-10T14:18:45.755476+00:00 [running]> on host 2c4b4cb333a5
[2024-06-10T14:19:12.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='21521333@gm.uit.edu.vn' AIRFLOW_CTX_DAG_OWNER='quan' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T14:18:45.755476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T14:18:45.755476+00:00'
[2024-06-10T14:19:12.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T14:19:12.990+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T14:19:12.991+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T14:19:13.005+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data, task_id=transform_data, run_id=manual__2024-06-10T14:18:45.755476+00:00, execution_date=20240610T141845, start_date=20240610T141912, end_date=20240610T141913
[2024-06-10T14:19:13.059+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T14:19:13.077+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T14:19:13.080+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
