[2024-06-10T14:04:38.679+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:04:38.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:04:38.683+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:04:38.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:04:38.707+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:04:38.703+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:04:38.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:04:38.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.057 seconds
[2024-06-10T14:05:09.819+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:09.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:05:09.823+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:05:09.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:09.859+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:05:09.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:05:09.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:09.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.070 seconds
[2024-06-10T14:05:40.314+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:40.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:05:40.318+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:05:40.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:40.352+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:05:40.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:05:40.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:05:40.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.063 seconds
[2024-06-10T14:06:10.885+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:06:10.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:06:10.890+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:06:10.889+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:06:10.923+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:06:10.915+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:06:10.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:06:10.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.086 seconds
[2024-06-10T14:07:09.488+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:09.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:07:09.497+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:07:09.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:09.518+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:07:09.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:07:09.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:10.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.640 seconds
[2024-06-10T14:07:43.039+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:43.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:07:43.045+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:07:43.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:43.078+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:07:43.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:07:43.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:07:43.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.080 seconds
[2024-06-10T14:08:13.990+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:13.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:08:13.995+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:08:13.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:14.023+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:08:14.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:08:14.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:14.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.076 seconds
[2024-06-10T14:08:44.608+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:44.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:08:44.613+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:08:44.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:44.647+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:08:44.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:08:44.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:08:44.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.072 seconds
[2024-06-10T14:09:15.366+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:15.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:09:15.370+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:09:15.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:15.396+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:09:15.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:09:15.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:15.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.057 seconds
[2024-06-10T14:09:45.867+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:45.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:09:45.871+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:09:45.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:45.901+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:09:45.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:09:45.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:09:45.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.066 seconds
[2024-06-10T14:10:16.450+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:16.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:10:16.455+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:10:16.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:16.478+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:10:16.472+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:10:16.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:16.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.058 seconds
[2024-06-10T14:10:47.088+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:47.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:10:47.092+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:10:47.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:47.112+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:10:47.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:10:47.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:10:47.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.057 seconds
[2024-06-10T14:11:17.630+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:17.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:11:17.633+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:11:17.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:17.650+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:11:17.646+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:11:17.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:17.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.043 seconds
[2024-06-10T14:11:48.151+0000] {processor.py:161} INFO - Started process (PID=655) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:48.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:11:48.154+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:11:48.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:48.172+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:11:48.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:11:48.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:11:48.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.047 seconds
[2024-06-10T14:12:18.474+0000] {processor.py:161} INFO - Started process (PID=724) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:18.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:12:18.477+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:12:18.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:18.497+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:12:18.493+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:12:18.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:18.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.048 seconds
[2024-06-10T14:12:49.195+0000] {processor.py:161} INFO - Started process (PID=793) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:49.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:12:49.199+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:12:49.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:49.228+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:12:49.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:12:49.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:12:49.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.060 seconds
[2024-06-10T14:13:19.446+0000] {processor.py:161} INFO - Started process (PID=862) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:19.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:13:19.450+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:13:19.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:19.481+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:13:19.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:13:19.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:19.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.063 seconds
[2024-06-10T14:13:50.026+0000] {processor.py:161} INFO - Started process (PID=931) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:50.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:13:50.032+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:13:50.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:50.051+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:13:50.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:13:50.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:13:50.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.646 seconds
[2024-06-10T14:14:21.553+0000] {processor.py:161} INFO - Started process (PID=1000) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:21.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:14:21.557+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:14:21.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:21.576+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:14:21.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:14:21.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:21.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.047 seconds
[2024-06-10T14:14:51.773+0000] {processor.py:161} INFO - Started process (PID=1069) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:51.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:14:51.777+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:14:51.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:51.799+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:14:51.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:14:51.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:14:51.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.058 seconds
[2024-06-10T14:15:21.975+0000] {processor.py:161} INFO - Started process (PID=1138) to work on /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:15:21.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_minio_s3.py for tasks to queue
[2024-06-10T14:15:21.979+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:15:21.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:15:22.019+0000] {logging_mixin.py:188} INFO - [2024-06-10T14:15:22.013+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_minio_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_minio_s3.py", line 4, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-06-10T14:15:22.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_minio_s3.py
[2024-06-10T14:15:22.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_minio_s3.py took 0.122 seconds
